version: '3.9'
name: "kpopit"

services:
  api:
    container_name: kpopit-api
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    depends_on:
      - db
    volumes:
      - ../:/app
      - /app/node_modules
    command: npm run dev

  db:
    container_name: kpopit-db-1
    image: postgres:15
    restart: always
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:  

