INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20130613, 'BTS', '#BF55FF');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20180325, 'Stray Kids', '#FF0000');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20190304, 'TXT', '#00FFFF');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20160808, 'Blackpink', '#FF21B3');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20190212, 'ITZY', '#FF00FF');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20140116, 'GOT7', '#00FF7F');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20150526, 'Seventeen', '#F7CAC9');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20231127, 'BabyMonster', '#A40000');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20240628, 'KATSEYE', '#FFFF4C');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20201130, 'Enhypen', '#FF7F1A');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20120408, 'EXO', '#D6C8AC');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20240906, 'MEOVV', '#FFCEEC');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20170113, 'Dreamcatcher', '#8A2A2B');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20180502, 'I-dle', '#5C068C');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20211201, 'IVE', '#FF1360');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20151020, 'Twice', '#FCC89B');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20230530, 'BOYNEXTDOOR', '#2596BE');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20230904, 'RIIZE', '#FD5E53');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20181024, 'ATEEZ', '#FF5101');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20230710, 'ZEROBASEONE', '#83C6BD');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20220502, 'Le Sserafim', '#7BA6DE');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20240325, 'ILLIT', '#D7D9FF');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20201117, 'aespa', '#87CEEB');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20220222, 'NMIXX', '#D67FF7');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20250120, 'KickFlip', '#A2A2A2');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20230705, 'Kiss of Life', '#E395C0');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20240122, 'TWS', '#4169E1');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20171206, 'The Boyz', '#4682B4');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20240228, 'NCT Wish', '#C6FFB2');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20160707, 'NCT 127', '#92FF04');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20160825, 'NCT Dream', '#92F36D');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20180124, 'fromis_9', '#FEF371');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20220722, 'NewJeans', '#323B80');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20230213, 'tripleS', '#FD01FB');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20201112, 'StayC', '#FD7190');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20150907, 'Day6', '#009193');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20140801, 'Red Velvet', '#9A0202');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20220302, 'Tempest', '#FFA830');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20230130, '8TURN', '#C06A71');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20220103, 'Ke1per', '#AE72E8');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20200807, 'Treasure', '#00CFFF');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20210315, 'Purple Kiss', '#4B1E47');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20221118, 'Fifty Fifty', '#E99ABE');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20240531, 'ARTMS', '#1B7BCA');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20150514, 'Monsta X', '#DC143C');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20160223, 'Astro', '#7F00FF');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20140618, 'Mamamoo', '#CED13E');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20201028, 'P1harmony', '#F88360');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20230330, 'Xikers', '#AAAAAA');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20120321, 'BTOB', '#42B4E6');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20220209, 'Viviz', '#ACBAE9');
INSERT INTO groups (debut_date, group_name, hex_code) VALUES (20190117, 'NCT WayV', '#AAF17D');

INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20010821, '8TURN', 'Myungho', 'Cho Myungho');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20021211, '8TURN', 'Jaeyun', 'Moon Jaeyun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20030826, '8TURN', 'Yungyu', 'Bang Yungyu');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20031016, '8TURN', 'Minho', 'Yoon Minho');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20050715, '8TURN', 'Kyungmin', 'Jung Kyungmin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20050830, '8TURN', 'Seongheon', 'Lee Seungheon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20060727, '8TURN', 'Haemin', 'Kim Haemin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20070803, '8TURN', 'Kyungmin', 'Lee Kyungmin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20000411, 'aespa', 'Karina', 'Yu Jimin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20001030, 'aespa', 'Giselle', 'Aeri Uchinaga');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20010101, 'aespa', 'Winter', 'Kim Minjeong');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20021023, 'aespa', 'Ningning', 'Ning Yizhou');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19970713, 'ARTMS', 'Jinsoul', 'Jeon Jinsol');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19970818, 'ARTMS', 'Haseul', 'Choi Haseul');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19990210, 'ARTMS', 'Kim Lip', 'Kim Jungeun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20001019, 'ARTMS', 'Heejin', 'Jeon Heejin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20010604, 'ARTMS', 'Choerry', 'Choi Yerim');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19940305, 'Astro', 'MJ', 'Kim Myungjun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19960315, 'Astro', 'Jinjin', 'Park Jinwoo');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19970330, 'Astro', 'Chae Eunwoo', 'Lee Dongmin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19980126, 'Astro', 'Moonbin', 'Moon Bin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20000321, 'Astro', 'Sanha', 'Yoon Sanha');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19980403, 'ATEEZ', 'Seonghwa', 'Park Seonghwa');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19981107, 'ATEEZ', 'Hongjoong', 'Kim Hongjoon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19990323, 'ATEEZ', 'Yunho', 'Jeong Yunho');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19990615, 'ATEEZ', 'Yeosang', 'Kang Yeosang');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19990710, 'ATEEZ', 'San', 'Choi San');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (1999080901, 'ATEEZ', 'Mingi', 'Song Mingi');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19991126, 'ATEEZ', 'Wooyoung', 'Jung Wooyoung');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20001012, 'ATEEZ', 'Jungho', 'Choi Jungho');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20020320, 'BabyMonster', 'Ruka', 'Kawai Ruka');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20050826, 'BabyMonster', 'Pharita', 'Pharita Boonpakdeethaveeyod');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20060417, 'BabyMonster', 'Asa', 'Enami Asa');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20070411, 'BabyMonster', 'Ahyeon', 'Jung Ahyeon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20071017, 'BabyMonster', 'Rami', 'Shin Rami');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20080814, 'BabyMonster', 'Rora', 'Lee Dain');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20090217, 'BabyMonster', 'Chiquita', 'Riracha Phondechaphiphat');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19950103, 'Blackpink', 'Jisoo', 'Kim Jisoo');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19960116, 'Blackpink', 'Jennie', 'Jennie Kim');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19970211, 'Blackpink', 'Rose', 'Park Chaeyoung');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19970327, 'Blackpink', 'Lisa', 'Lalisa Manobal');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20030904, 'BOYNEXTDOOR', 'Sungho', 'Park Sungho');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20031022, 'BOYNEXTDOOR', 'Riwoo', 'Lee Sanghyeok');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (2003120401, 'BOYNEXTDOOR', 'Jaehyun', 'Myung Jaehyun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20040810, 'BOYNEXTDOOR', 'Taesan', 'Han Dongmin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20041020, 'BOYNEXTDOOR', 'Leehan', 'Kim Donghyun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20061129, 'BOYNEXTDOOR', 'Woonhak', 'Kim Woonhak');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19901022, 'BTOB', 'Eunkwang', 'Seo Eunkwang');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19901129, 'BTOB', 'Minhyuk', 'Lee Minhyuk');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19910226, 'BTOB', 'Changsub', 'Lee Changsub');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19920307, 'BTOB', 'Hyunsik', 'Im Hyunsik');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19930310, 'BTOB', 'Peniel', 'Peniel Dong Shin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19950502, 'BTOB', 'Sungjae', 'Yook Sungjae');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19921204, 'BTS', 'Jin', 'Kim Seokjin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19930309, 'BTS', 'Suga', 'Min Yoongi');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19940218, 'BTS', 'J Hope', 'Jung Hoseok');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19940912, 'BTS', 'RM', 'Kim Namjoon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19951013, 'BTS', 'Jimin', 'Park Jimin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (1995123001, 'BTS', 'V', 'Kim Taehyung');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19970901, 'BTS', 'Jungkook', 'Jeon Jungkook');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19930116, 'Day6', 'Sungjin', 'Park Sungjin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19931219, 'Day6', 'Young K', 'Kang Younghyun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19940428, 'Day6', 'Wonpil', 'Kim Wonpil');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19950825, 'Day6', 'Dowoon', 'Yoon Dowoon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19940517, 'Dreamcatcher', 'JiU', 'Kim Minji');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19940810, 'Dreamcatcher', 'SuA', 'Kim BoRa');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19951001, 'Dreamcatcher', 'Siyeon', 'Lee Siyeon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19960326, 'Dreamcatcher', 'Handong', 'Han Dong');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19970107, 'Dreamcatcher', 'Yoohyeon', 'Kim Yoohyeon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19970307, 'Dreamcatcher', 'Dami', 'Lee Yubin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19990203, 'Dreamcatcher', 'Gahyeon', 'Lee Gahyeon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20011015, 'Enhypen', 'Heeseung', 'Lee Heeseung');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20020420, 'Enhypen', 'Jay', 'Jay Park');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20021115, 'Enhypen', 'Jake', 'Jake Sim');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20021208, 'Enhypen', 'Sunghoon', 'Park Sunghoon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20030624, 'Enhypen', 'Sunoo', 'Kim Sunoo');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20040209, 'Enhypen', 'Jungwon', 'Yang Jungwon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20051209, 'Enhypen', 'Ni-Ki', 'Nishimura Riki');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19900326, 'EXO', 'Xiumin', 'Kim Minseok');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19910522, 'EXO', 'Suho', 'Kim Junmyeon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19911007, 'EXO', 'Lay', 'Zhang Yixing');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19920506, 'EXO', 'Baekhyun', 'Byun Baehyun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19920921, 'EXO', 'Chen', 'Kim Jongdae');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19921127, 'EXO', 'Chanyeol', 'Park Chanyeol');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19930112, 'EXO', 'D.O.', 'Do Kyungsoo');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19940114, 'EXO', 'Kai', 'Kim Jongin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19940412, 'EXO', 'Sehun', 'Oh Sehun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20030709, 'Fifty Fifty', 'Keena', 'Song Jakyung');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20040714, 'Fifty Fifty', 'Chanelle Moon', 'Chanelle Moon Thomas');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20050318, 'Fifty Fifty', 'Yewon', 'Son Yewon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20060905, 'Fifty Fifty', 'Hana', 'Lim Haram');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20070315, 'Fifty Fifty', 'Athena', 'Athena Yang Yang Tzuhsien');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19970929, 'fromis_9', 'Hayoung', 'Song Hayoung');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19980320, 'fromis_9', 'Jiwon', 'Park Jiwon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20000514, 'fromis_9', 'Chaeyoung', 'Lee Chaeyoung');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20000601, 'fromis_9', 'Nagyung', 'Lee Nagyung');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20030417, 'fromis_9', 'Jiheon', 'Baek Jiheon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19930904, 'GOT7', 'Mark', 'Mark Tuan');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19940106, 'GOT7', 'Jay B', 'Lim Jaebom');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19940328, 'GOT7', 'Jackson', 'Jackson Wang');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19940922, 'GOT7', 'Jinyoung', 'Park Jinyoung');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19960917, 'GOT7', 'YoungJae', 'Choi Youngjae');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19970502, 'GOT7', 'BamBam', 'Kunpimook Bhuwaku');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19971117, 'GOT7', 'Yugyeom', 'Kim Yugyeom');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19970131, 'I-dle', 'Miyeon', 'Choi Miyeon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19971023, 'I-dle', 'Minnie', 'Nicha Yontararak');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19980826, 'I-dle', 'Soyeon', 'Jeon Soyeon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19990923, 'I-dle', 'Yuqi', 'Song Yuqi');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20000106, 'I-dle', 'Shuhua', 'Yeh Shuhua');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20040115, 'ILLIT', 'Yunah', 'Noh Yunah');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20040511, 'ILLIT', 'Minju', 'Park Minju');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20041008, 'ILLIT', 'Moka', 'Sakai Moka');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20070626, 'ILLIT', 'Wonhee', 'Lee Wonhee');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20080204, 'ILLIT', 'Iroha', 'Hokazono Iroha');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20000526, 'ITZY', 'Yeji', 'Hwang Yeji');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20000721, 'ITZY', 'Lia', 'Choi Jisu');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20010417, 'ITZY', 'Ryujin', 'Shin Ryujin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20010605, 'ITZY', 'Chaeryeong', 'Lee Chaeryeong');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20031209, 'ITZY', 'Yuna', 'Shin Yuna');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20020924, 'IVE', 'Gaeul', 'Kim Gaeul');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20030901, 'IVE', 'Yujin', 'An Yujin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20040203, 'IVE', 'Rei', 'Naoi Rei');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20040831, 'IVE', 'Wonyoung', 'Jang Wonyoung');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20041121, 'IVE', 'Liz', 'Kim Jiwon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20070221, 'IVE', 'Leeseo', 'Lee Hyunseo');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20020626, 'Katseye', 'Manon', 'Manon Bannerman');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20021231, 'Katseye', 'Sophia', 'Sophia Laforteza');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20040721, 'Katseye', 'Daniela', 'Daniela Avanzini');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20051103, 'Katseye', 'Lara', 'Lara Rajagopalan');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20060210, 'Katseye', 'Megan', 'Megan Skiendiel');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20071206, 'Katseye', 'Yoonchae', 'Jeon Yoonchae');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19960812, 'Ke1per', 'Yujin', 'Choi Yujin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19991112, 'Ke1per', 'Xiaoting', 'Shen Xiating');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20020426, 'Ke1per', 'Chaehyun', 'Kim Chaehyun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20030302, 'Ke1per', 'Dayeon', 'Kim Dayeon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20040312, 'Ke1per', 'Hikaru', 'Ezaki Hikaru');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20040727, 'Ke1per', 'Bahiyyih', 'Huening Bahiyyih');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20041227, 'Ke1per', 'Youngeun', 'Seo Youneun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20040916, 'KickFlip', 'Kyehoon', 'Lee Gyehun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (2005102101, 'KickFlip', 'Amaru', 'Mitsuyuki Amaru');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20060311, 'KickFlip', 'Donghwa', 'Lee Donghwa');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20060502, 'KickFlip', 'Juwang', 'Jang Juwang');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20060512, 'KickFlip', 'Minje', 'Choi Minje');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20061004, 'KickFlip', 'Keiju', 'Okamoto Keiju');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20070313, 'KickFlip', 'Donghyeon', 'Lee Donghyeon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20000329, 'Kiss of Life', 'Julie', 'Julie Han');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20020530, 'Kiss of Life', 'Natty', 'Ahnatchaya Suputhipong');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20040320, 'Kiss of Life', 'Belle', 'Annabelle Shim');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20050525, 'Kiss of Life', 'Haneul', 'Won Haneul');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19980319, 'Le Sserafim', 'Sakura', 'Miyawaki Sakura');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20000801, 'Le Sserafim', 'Chaewon', 'Kim Chaewon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20011008, 'Le Sserafim', 'Yunjin', 'Huh Yunjin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20030809, 'Le Sserafim', 'Kazuha', 'Nakamura Kazuha');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20061110, 'Le Sserafim', 'Eunchae', 'Hong Eunchae');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19910221, 'Mamamoo', 'Solar', 'KimYongsun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19921222, 'Mamamoo', 'Moonbyul', 'Moon Byulyi');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19950417, 'Mamamoo', 'Wheein', 'Jung Wheein');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19950723, 'Mamamoo', 'Hwasa', 'Ahn Heyjin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20050412, 'Meovv', 'Sooin', 'Kim Sooin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20050427, 'Meovv', 'Gawon', 'Lee Gawon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20051117, 'Meovv', 'Anna', 'Tanaka Anna');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20070815, 'Meovv', 'Narin', 'Na Rin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20081201, 'Meovv', 'Ella', 'Ella McKenzie Gross');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19920618, 'Monsta X', 'Shownu', 'Son Hyunwoo');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19931103, 'Monsta X', 'Minhyuk', 'Lee Minhyuk');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19931122, 'Monsta X', 'Kihyun', 'Yoo Kihyun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19940115, 'Monsta X', 'Hyungwon', 'Chae Hungwon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19941006, 'Monsta X', 'Joohoney', 'Lee Jooheon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19960126, 'Monsta X', 'I.M', 'Im Changkyun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19950209, 'NCT 127', 'Johnny', 'John Suh');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19950701, 'NCT 127', 'Taeyong', 'Lee Taeyong');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19960201, 'NCT 127', 'Doyoung', 'Kim Dongyoung');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19961126, 'NCT 127', 'Yuta', 'Nakamoto Yuta');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19970214, 'NCT 127', 'Jaehyun', 'Jeong Yuno');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19980219, 'NCT 127', 'Jungwoo', 'Kim Jungwoo');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19990802, 'NCT 127', 'Mark', 'Mark Lee');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20000606, 'NCT 127', 'Haechan', 'Lee Dongyuck');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20000323, 'NCT Dream', 'Renjun', 'Huang Renjun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20000423, 'NCT Dream', 'Jeno', 'Lee Jeno');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20000813, 'NCT Dream', 'Jaemin', 'Na Jaemin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20011122, 'NCT Dream', 'Chenle', 'Zhong Chenle');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (2002020502, 'NCT Dream', 'Jisung', 'Park Jisung');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19960101, 'NCT WayV', 'Kun', 'Qian Kun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19960227, 'NCT WayV', 'Ten', 'Chittaphon Leechaiyapornkul');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19971028, 'NCT WayV', 'Winwin', 'Dong Sicheng');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19990808, 'NCT WayV', 'Xiaojun', 'Xiao Dejun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19990928, 'NCT WayV', 'Hendery', 'Wong Kunhang');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20001010, 'NCT WayV', 'Yangyang', 'Liu Yangyang');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20020511, 'NCT Wish', 'Sion', 'Oh Sion');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20030628, 'NCT Wish', 'Riku', 'Maeda Riku');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (2004040501, 'NCT Wish', 'Yushi', 'Tokuno Yushi');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20050621, 'NCT Wish', 'Jaehee', 'Kim Daeyoung');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20070804, 'NCT Wish', 'Ryo', 'Hirose Ryo');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20071118, 'NCT Wish', 'Sakuya', 'Fujinaga Sakuya');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20040507, 'NewJeans', 'Minji', 'Kim Minji');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20041005, 'NewJeans', 'Hanni', 'Hanni Pham');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20050411, 'NewJeans', 'Danielle', 'Danielle June Marsh');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20060515, 'NewJeans', 'Haerin', 'Kang Haerin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20080421, 'NewJeans', 'Hyein', 'Lee Hyein');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20021017, 'NMIXX', 'Lily', 'Lily Jin Morrow');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20030225, 'NMIXX', 'Haewon', 'Oh Haewon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20040126, 'NMIXX', 'Sullyoon', 'Seol Yoona');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20041228, 'NMIXX', 'Bae', 'Bae Jinsol');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20050413, 'NMIXX', 'Jiwoo', 'Kim Jiwoo');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20060526, 'NMIXX', 'Kyujin', 'Jang Kyujin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20010701, 'P1harmony', 'Theo', 'Choi Taeyang');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20010927, 'P1harmony', 'Keeho', 'Yoon Keho');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20011007, 'P1harmony', 'Jiung', 'Choi Jiung');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20030831, 'P1harmony', 'Intak', 'Hwang Intak');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20050201, 'P1harmony', 'Soul', 'Haka Shota');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20051119, 'P1harmony', 'Jongseob', 'Kim Jongseob');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19990903, 'Purple Kiss', 'Goeun', 'Na Goeun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20000211, 'Purple Kiss', 'Dosie', 'Jang Eunseong');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20020430, 'Purple Kiss', 'Ireh', 'Cho Seoyoung');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20021106, 'Purple Kiss', 'Yuki', 'Mori Koyuki');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20021205, 'Purple Kiss', 'Chaein', 'Lee Chaeyoung');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20030711, 'Purple Kiss', 'Swan', 'Park Sujin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19910329, 'Red Velvet', 'Irene', 'Bae Juhyun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19940210, 'Red Velvet', 'Seulgi', 'Kang Seulgi');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19940221, 'Red Velvet', 'Wendy', 'Wendy Shon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19960903, 'Red Velvet', 'Joy', 'Park Sooyoung');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19990305, 'Red Velvet', 'Yeri', 'Kim Yerim');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20001125, 'RIIZE', 'Shotaro', 'Osaki Shotaro');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20010319, 'RIIZE', 'Eunseok', 'Song Eunseok');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20010913, 'RIIZE', 'Sungchan', 'Jung Sungchan');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20020302, 'RIIZE', 'Wonbin', 'Park Wonbin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20031121, 'RIIZE', 'Sohee', 'Lee Sohee');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20040321, 'RIIZE', 'Anton', 'Lee Chanyoung');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19950808, 'Seventeen', 'S.Coups', 'Choi  Seungcheol');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19951004, 'Seventeen', 'Jeonhan', 'Yoon Jeonhan');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (1995123002, 'Seventeen', 'Joshua', 'Joshua Hong');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19960610, 'Seventeen', 'Jun', 'Wen Junhui');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19960615, 'Seventeen', 'Hoshi', 'Kwon Soonyoung');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19960717, 'Seventeen', 'Wonwoo', 'Jeon Wonwoo');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19961122, 'Seventeen', 'Woozi', 'Lee Jihoon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19970218, 'Seventeen', 'DK', 'Lee Seokmin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19970406, 'Seventeen', 'Mingyu', 'Kim Mingyu');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19971107, 'Seventeen', 'The8', 'Xu Minghao');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19980116, 'Seventeen', 'Seungkwan', 'Boo Seungkwan');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19980218, 'Seventeen', 'Vermon', 'Hansol Vernon Chwe');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19990211, 'Seventeen', 'Dino', 'Lee Chan');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (2001031302, 'StayC', 'Sumin', 'Bae Sumin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20010801, 'StayC', 'Sieun', 'Park Sieun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20020123, 'StayC', 'Isa', 'Lee Chaeyoung');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20030614, 'StayC', 'Seeun', 'Yoon Seeun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20040414, 'StayC', 'Yoon', 'Sim Jayun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20041209, 'StayC', 'J', 'Jang Yeeun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19971003, 'Stray Kids', 'Bang Chan', 'Christopher Bang');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19981025, 'Stray Kids', 'Lee Know', 'Lee Minho');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19990811, 'Stray Kids', 'Changbin', 'Seo Changbin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20000320, 'Stray Kids', 'Hyunjin', 'Hwang Hyunjin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20000914, 'Stray Kids', 'Han', 'Han Jisung');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20000915, 'Stray Kids', 'Felix', 'Lee Felix');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20000922, 'Stray Kids', 'Seungmin', 'Kim Seungmin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20010208, 'Stray Kids', 'I.N', 'Yang Jeonin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19980119, 'Tempest', 'Hanbin', 'Ngô Ngọc Hưng');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (1999080902, 'Tempest', 'Hyeongseop', 'Ahn Heyeongseop');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20000417, 'Tempest', 'Hyuk', 'Koo Bonhyuk');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20010227, 'Tempest', 'Eunchan', 'Choi Byeongseop');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20010405, 'Tempest', 'Lew', 'Lee Euiwoong');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20020509, 'Tempest', 'Taerae', 'Kim Taerae');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19961104, 'The Boyz', 'Sanyeon', 'Lee Sangyeon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (1997053001, 'The Boyz', 'Jacob', 'Jacob Bae');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19970808, 'The Boyz', 'Younghoon', 'Kim Younghoon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19970913, 'The Boyz', 'Hyunjae', 'Lee Jaehyun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19980115, 'The Boyz', 'Juyeon', 'Lee Juyeon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19980223, 'The Boyz', 'Kevin', 'Kevin Moon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19980426, 'The Boyz', 'New', 'Choi Chanhee');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19981105, 'The Boyz', 'Q', 'Ji Changmin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20000412, 'The Boyz', 'Sunwoo', 'Kim Sunwoo');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20001222, 'The Boyz', 'Eric', 'Son Youngjae');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19990421, 'Treasure', 'Hyunsuk', 'Choi Hyunsuk');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20000314, 'Treasure', 'Jihoon', 'Park Jihoon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20000515, 'Treasure', 'Yoshi', 'Kanameto Yoshinori');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20000909, 'Treasure', 'Junkyu', 'Kim Junkyu');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20010723, 'Treasure', 'Jaehyuk', 'Yoon Jaehyuk');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20010820, 'Treasure', 'Asahi', 'Hamada Asahi');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (2003120402, 'Treasure', 'Doyoung', 'Kim Doyoung');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (2004040502, 'Treasure', 'Haruto', 'Watanabe Haruto');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20040928, 'Treasure', 'Jeongwoo', 'Park Jeongwoo');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20010209, 'tripleS', 'Yooyeon', 'Kim Yooyeon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20020512, 'tripleS', 'Mayu', 'Koma Mayu');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20020525, 'tripleS', 'Xinyu', 'Zhou Xinyu');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (2002101301, 'tripleS', 'Nakyoung', 'Kim Nakyoung');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (2002101302, 'tripleS', 'Sohyun', 'Park Sohyun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20030108, 'tripleS', 'Seoyeon', 'Yoon Seoyeon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20030602, 'tripleS', 'Nien', 'Hsu Nientzu');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20040213, 'tripleS', 'JiYeon', 'Ji Suhyeon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20040310, 'tripleS', 'Kotone', 'Kamimoto Kotone');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (2004120401, 'tripleS', 'Chaeyeon', 'Kim Chaeyeon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20050203, 'tripleS', 'Yubin', 'Gong Yubin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20051120, 'tripleS', 'Kaede', 'Yamada Kaede');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20060403, 'tripleS', 'Shion', 'Park Shion');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20060412, 'tripleS', 'Lynn', 'Kawakami Rin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20061130, 'tripleS', 'Sullin', 'Pirada Bunraksa');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20070412, 'tripleS', 'Hyerin', 'Jeon Hyerin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20070502, 'tripleS', 'Chaewon', 'Kim Chaewon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20070801, 'tripleS', 'Hayeon', 'Jeon Hayeon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20071003, 'tripleS', 'Soomin', 'Kim Soomin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20080108, 'tripleS', 'Yeonji', 'Kwak Yeonji');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20090116, 'tripleS', 'Joo Bin', 'Joo Bin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20100412, 'tripleS', 'SeoAh', 'Jeon Haerin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19950912, 'Twice', 'Nayeon', 'Im Nayeon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19961101, 'Twice', 'Jeongyeon', 'Yoon Jeongyeon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19961109, 'Twice', 'Momo', 'Hirai Momo');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19961229, 'Twice', 'Sana', 'Minatozaki Sana');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19970201, 'Twice', 'Jihyo', 'Park Jihyo');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19970324, 'Twice', 'Mina', 'Myoi Mina');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19980528, 'Twice', 'Dahyun', 'Kim Dahyun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19990423, 'Twice', 'Chaeyeong', 'Son Chaeyeong');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19990614, 'Twice', 'Tzuyu', 'Chou Tzuyu');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20031107, 'TWS', 'Shinyu', 'Shin Junghwan');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20050130, 'TWS', 'Dohoon', 'Kim Dohoon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20050531, 'TWS', 'Youngjae', 'Choi Youngjae');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20060105, 'TWS', 'Hanjin', 'Han Zhen');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20060328, 'TWS', 'Jihoon', 'Han Jihoon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20071002, 'TWS', 'Kyungmin', 'Lee Kyungmin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19990913, 'TXT', 'Yeonjun', 'Choi Yeonjun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20001205, 'TXT', 'Soobin', 'Choi Soobin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (2001031301, 'TXT', 'Beomgyu', 'Choi Beomgyu');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (2002020501, 'TXT', 'Taehyun', 'Kang Taehyun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20020814, 'TXT', 'HueningKai', 'Kai Kamal Huening');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (1997053002, 'Viviz', 'Eunha', 'Jung Eunbi');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19980603, 'Viviz', 'SinB', 'Hwang Eunbi');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19980819, 'Viviz', 'Umji', 'Kim Yewon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20030410, 'Xikers', 'Minjae', 'Kim Minjae');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20030524, 'Xikers', 'Junmin', 'Park Junmin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20040407, 'Xikers', 'Sumin', 'Choi Sumin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20040730, 'Xikers', 'Jinsik', 'Ham Jinsik');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (2004120402, 'Xikers', 'Hyunwoo', 'Choi Hyunwoo');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20050705, 'Xikers', 'Junghoon', 'Kim Junghoon');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20050827, 'Xikers', 'Seeun', 'Park Seeun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (2005102102, 'Xikers', 'Yechan', 'Lee Yechan');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (2005100501, 'Xikers', 'Yujun', 'Jung Yujun');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (2005100502, 'Xikers', 'Hunter', 'Papungkorn Lertkiatdamrong');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (19981214, 'ZEROBASEONE', 'Jiwoong', 'Kim Jiwoong');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20000725, 'ZEROBASEONE', 'ZhangHao', 'Zang Hao');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20010613, 'ZEROBASEONE', 'Hanbin', 'Sung Hanbin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20020528, 'ZEROBASEONE', 'Matthew', 'Seok Matthew');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20020714, 'ZEROBASEONE', 'Taerae', 'Kim Taerae');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20040520, 'ZEROBASEONE', 'Ricky', 'Shen Quanrui');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20040830, 'ZEROBASEONE', 'Gyuvin', 'Kim Gyuvin');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20050110, 'ZEROBASEONE', 'Gunwook', 'Park Gunwook');
INSERT INTO idols (birthday, group_name, stage_name, legal_name) VALUES (20070320, 'ZEROBASEONE', 'Yujin', 'Han Yujin');